// ReSharper disable InconsistentNaming

using System;

namespace ETD.Scripts.Common
{
    public enum EquippedPositionType
    {
        Active,
        Link,
        Passive
    }

    public enum EnemyType
    {
        Melee,
        Range,
        BossMelee,
        DiaBoss,
        GuildBossFire,
    }

    public enum ElementalType
    {
        Fire,
        Water,
        Wind,
        Lighting,
        Light,
        Darkness
    }

    public enum RuneType
    {
        Projectile,
        Expansion,
        Chain,
        Amplify,
        AttackSpeed,
        Duration,
        RandomTag
    }

    public enum TagType
    {
        Projectile = 0,
        Expansion,
        Chain,
        Duration,
        Fire,
        Water,
        Wind,
        Lighting,
        Light,
        Darkness
    }

    public enum GradeType
    {
        C,
        B,
        A,
        S,
        SS,
        SSS
    }

    public enum ColorType
    {
        SkyBlue,
        Red,
    }

    public enum AttributeType
    {
        None = -1,
        Atk = 0,
        FAtk,
        IAtk,
        WAtk,
        LgAtk,
        LAtk = 5,
        DAtk,
        AddAtk,
        AddFAtk,
        AddIAtk,
        AddWAtk = 10,
        AddLgAtk,
        AddLAtk,
        AddDAtk,
        
        Projectile,
        Expansion = 15,
        Chain,
        Amplify,
        AttackSpeed,
        Duration,
        RandomTag = 20,
        
        CriticalRate,
        CriticalDamage,
        
        AddMaxHp,
        AddGoldGain,
        GameSpeed,
    }

    //순서 값 바뀜
    public enum GoodType
    {
        None = -1,
        Dia = 0,
        Gold,
        ElementalEnhancementStone,
        RuneEnhancementStone,
        ShowAds,
        SummonElemental,
        SummonRune,
        SummonElementalTicket,
        SummonRuneTicket,
        RemoveAds,
        GoldDungeonTicket,
        GemDungeonTicket,
        EnhanceDungeonTicket,
        DungeonTickets,
        DarkDia,
        SpecialLab,
        RaidTicket,
        Protection,
        VIP,
        IncreaseStageReward,
        IncreaseGameSpeed,
        IncreaseDungeonReward,
        IncreaseLabSpeed,
        
        SummonElementalS,
        SummonElementalSS,
        SummonRuneS,
        SummonRuneSS,
        
        GuildExp,
        GuildGiftBoxPoint,
        GuildGiftBoxExp,
        GuildRaidTicket,
        GuildToken,
    }

    public enum ProbabilityType
    {
        SummonElemental,
        SummonRune,
        GuildRaidBox,
    }

    public enum UpgradeType
    {
        IncreaseBaseAtkPower,
        IncreaseCriticalRate,
        IncreaseCriticalPower,
        IncreaseMaxHp,
        IncreaseHealAmountPerSecond,
        IncreaseTotalAtkRate,
        
        IncreaseProjector,
        IncreaseElementalUnit,
        IncreaseRuneUnit,
    }

    public enum LocalizedTextType
    {
        UpgradeTitle,
        UpgradeMaxTitle,
        UpgradeIncreaseBaseAtkPower,
        UpgradeIncreaseCriticalRate,
        UpgradeIncreaseCriticalPower,
        UpgradeIncreaseMaxHp,
        UpgradeIncreaseHealAmountPerSecond,
        UpgradeIncreaseTotalAtkRate,
        UpgradeIncreaseProjector,
        UpgradeIncreaseElementalUnit,
        UpgradeIncreaseRuneUnit,

        SlotIsLock,
        EmptySlotMessage,

        Enhancement,
        Enhance,
        EnhanceSuccess,
        EnhanceFail,
        EnhanceMaxLevel,
        EnhanceNoMore,
        EnhanceProbability,

        Disassembly,
        AutoDisassemblySetting,
        AutoAdd,
        PleaseSelectDisassembleUnit,

        Equipment,
        Equipped,

        RewardTitle,
        ClearTitle,
        Lv,
        LevelUp,

        AfterScondsMoveToPreviousStage,
        TabToClose,

        ShowAdsCountForFreeReward,

        Shop_TopSeller,
        Shop_Summon,
        Shop_SummonElemental,
        Shop_SummonRune,
        Shop_Gems,
        Shop_CurrPurchasedCount,
        Shop_PackageValue,

        etd_newbiepackage,

        Setting,
        Setting_ETC,
        Setting_BGMSound,
        Setting_EffectSound,
        Setting_CameraShake,
        Setting_AutoSleep,
        Setting_Language,
        Setting_GameSetting,
        Setting_AccountSetting,
        Setting_AccountConnect,
        Setting_Mail,
        Setting_GoogleLogin,
        Setting_AppleLogin,
        Setting_Logout,
        Setting_AccountDelete,
        Setting_PrivatePolicy,
        Setting_TermsOfUse,
        Setting_OpenSourceLicense,

        Mail,
        Mail_ErrorRewardTitle,
        Mail_ErrorRewardDesc,
        Mail_MaintenanceRewardTitle,
        Mail_MaintenanceRewardDesc,
        Mail_RemainingDays,

        Stage,
        Ranking,
        Ranking_StageRanking,
        Ranking_Power,
        Ranking_RefreshTimeDesc,

        Quest_KillEnemy,
        Quest_SummonElemental,
        Quest_SummonRune,
        Quest_ClearNormalStage,
        Quest_ClearGoldDungeon,
        Quest_ClearDiaDungeon,
        Quest_ClearEnhanceDungeon,
        Quest_UpgradeElementalSlot,
        Quest_EquipElemental,
        Quest_UpgradeRuneSlot,
        Quest_EquipRune,
        Quest_UpgradeProjector,
        Quest_EquipElementalWithProjector,
        Quest_EquipRuneWithProjector,
        Quest_UpgradeATK,
        Quest_UpgradeMaxHp,
        Quest_UpgradeIncreaseHealAmount,
        Quest_EnhanceElemental,
        Quest_EnhanceRune,
        Quest_DisassembleRune,

        Dungeon_GoldDungeon,
        Dungeon_DiaDungeon,
        Dungeon_EnhanceStoneDungeon,
        Dungeon_GoldDungeonDescription,
        Dungeon_DiaDungeonDescription,
        Dungeon_EnhanceStoneDungeonDescription,
        Dungeon_GoldDungeonGoal,
        Dungeon_DiaDungeonGoal,
        Dungeon_EnhanceStoneDungeonGoal,
        Dungeon_Toast_ExitTitle,
        Dungeon_Toast_ExitDescription,
        Dungeon_Toast_ContinueButton,
        Dungeon_Toast_ExitButton,
        Dungeon_Toast_NextLevel,
        Dungeon_Sweep,
        Dungeon_SweepTitle,

        Min,
        Max,
        Confirm,
        Cancel,
        Load,
        GetReward,
        GetAllReward,

        Seconds,

        Nickname,
        Nickname_PlaseInputNickname,
        Nickname_Description,
        Nickname_Duplicate,
        Nickname_BadParameter_UnavailableName,
        Nickname_BadParameter_NameIsToShort,
        Nickname_FreeOneChance,
        Nickname_ChangeNicknameSuccess,
        NotEnoughGoods,

        Copy,
        CopySuccess,

        net_themessage_etc_dia0,
        net_themessage_etc_dia1,
        net_themessage_etc_dia2,
        net_themessage_etc_dia3,
        net_themessage_etc_dia4,
        net_themessage_etc_dia5,
        net_themessage_etc_newbiepackage,
        net_themessage_etc_removeadspackage,
        net_themessage_etc_summonticketpackage0,

        FederationLoginSuccess,
        hasFederationDataMessage,
        CloudUpload,
        UploadMessage,

        Warring,
        Warring_Logout,
        Warring_DeleteAccount,
        Warring_UpdateNotice,
        Warring_UpdateForce,
        Warring_WaitForSeconds,
        Warring_QuitApplication,

        ErrorMessage,
        Error_LoginFails,
        Error_BlockedUser,
        Error_GoogleLoginFails,
        Error_AppleLoginFails,
        Error_OtherDeviceLogin,
        Error_MaintenanceError,
        Error_DeviceBlockError,

        Mission_title,
        Mission_Daily,
        Mission_Weekly,
        Mission_Repeat,

        Mission_DailyLogin,
        Mission_KillEnemy,
        Mission_ClearGoldDungeon,
        Mission_ClearDiaDungeon,
        Mission_ClearEnhanceDungeon,
        Mission_ClearNormalStage,
        Mission_ClearAnyDungeon,
        Mission_SummonElemental,
        Mission_SummonRune,
        Mission_Enhance,
        Mission_Upgrade,

        PowerSaving,
        PowerSaving_StageProcessing,
        PowerSaving_Release,

        UnlockCondition,
        UnlockConditionLongText,

        RuneType_Projectile,
        RuneType_Expansion,
        RuneType_Chain,
        RuneType_Amplify,
        RuneType_AttackSpeed,
        RuneType_Duration,
        RuneType_RandomTag,

        TagType_Projectile,
        TagType_Expansion,
        TagType_Chain,
        TagType_Duration,
        TagType_Fire,
        TagType_Water,
        TagType_Wind,
        TagType_Lighting,
        TagType_Light,
        TagType_Darkness,

        AttributeType_Atk,
        AttributeType_FAtk,
        AttributeType_IAtk,
        AttributeType_WAtk,
        AttributeType_LgAtk,
        AttributeType_LAtk,
        AttributeType_DAtk,
        AttributeType_AddAtk,
        AttributeType_AddFAtk,
        AttributeType_AddIAtk,
        AttributeType_AddWAtk,
        AttributeType_AddLgAtk,
        AttributeType_AddLAtk,
        AttributeType_AddDAtk,
        AttributeType_Projectile,
        AttributeType_Expansion,
        AttributeType_Chain,
        AttributeType_Amplify,
        AttributeType_AttackSpeed,
        AttributeType_Duration,
        AttributeType_RandomTag,
        AttributeType_CriticalRate,
        AttributeType_CriticalDamage,

        BottomMenu_Elemental,
        BottomMenu_Rune,
        BottomMenu_Upgrade,
        BottomMenu_Dungeon,
        BottomMenu_Shop,

        Dungeon_Title,
        Dungeon_Description,

        Enter,
        Reward,
        AllClassification,
        DescendingGrade,
        AscendingGrade,
        EquipEffect,
        EmptyRune,
        EarnedEffect,
        SeeAll,
        SeeEarned,
        RuneType,
        Grade,
        EmptyMail,
        CurrStage,
        BeforeReaching,
        AdIsNotReady,

        SummonOnce,
        Summon11Times,

        net_themessage_etd_removeadspackage,
        SummonProbability,
        FreeGiftsTitle,
        FreeCoin,
        FreeSummonTicket,
        FreeDungeonTicket,

        PurchaseCount,

        net_themessage_etd_stagepackage0,
        net_themessage_etd_stagepackage1,
        net_themessage_etd_stagepackage2,
        net_themessage_etd_stagepackage3,
        net_themessage_etd_stagepackage4,
        net_themessage_etd_stagepackage5,
        net_themessage_etd_stagepackage6,
        net_themessage_etd_stagepackage7,
        net_themessage_etd_stagepackage8,
        net_themessage_etd_stagepackage9,

        NotAcquired,
        SelectEquipSlot,

        TutorialEquipElemental0,
        TutorialEquipElemental1,
        TutorialEquipRune0,
        TutorialEquipRune1,

        RuneDisassembleRewardDiscription,
        GetReward2X,
        OfflineRewardTitle,
        OfflineRewardTime,
        OfflineRewardDescription,
        GameSpeedUpTitle,
        GameSpeedUpDescription,
        ShowAds,
        GoToRemoveAds,
        AllSummonOpen,
        SummonEffectSkip,
        ReSummon,

        TutorialScript_StartGame_0,
        TutorialScript_StartGame_1,
        TutorialScript_StartGame_2,

        TutorialScript_GameSpeed_0,
        TutorialScript_GameSpeed_1,
        Quest_GameSpeed,

        Buff_Title,
        Buff_Description,

        AttributeType_AddMaxHp,
        AttributeType_AddGoldGain,
        AttributeType_GameSpeed,
        TotalGameSpeedDesc,

        Quest_GameSpeedBuff,

        TutorialScript_Buff_0,
        TutorialScript_Buff_1,

        Attendance_SevenDays,
        Days,

        FirstPurchaseReward_Title,
        FirstPurchaseReward_Description,
        FirstPurchaseReward_IconTitle,

        Pass_Title,
        Pass_PremiumPass,
        Pass_MasterPass,
        Pass_NormalPass,
        Pass_Description0,
        Pass_Description1,
        Change,

        TutorialScript_DescriptionActiveSlot_0,
        TutorialScript_DescriptionLinkSlot_0,
        TutorialScript_DescriptionPassiveSlot_0,
        ActiveSlot,
        LinkSlot,
        PassiveSlot,

        EquipText,
        UnEquipText,
        Setting_FrameRate,
        UnlockUpgradeProjector,

        IsRunePull,

        TutorialScript_SummonElemental_0,
        TutorialScript_SummonElemental_1,
        TutorialScript_UpgradeElementalSlot_0,
        TutorialScript_UpgradeElementalSlot_1,
        TutorialScript_UpgradeElementalSlot_2,
        TutorialScript_DescriptionSlot_0,
        TutorialScript_SummonRune_0,
        TutorialScript_SummonRune_1,
        TutorialScript_SummonRune_2,
        TutorialScript_UpgradeRuneSlot_0,
        TutorialScript_UpgradeRuneSlot_1,
        TutorialScript_UpgradeRuneSlot_2,
        TutorialScript_EquipRune_0,
        TutorialScript_EquipRune_1,
        TutorialScript_EquipRune_2,
        TutorialScript_EquipRune_3,
        TutorialScript_EquipRune_4,
        TutorialScript_EquipRune_5,
        TutorialScript_GoldDungeon_0,
        TutorialScript_GoldDungeon_1,
        TutorialScript_DiaDungeon_0,
        TutorialScript_DiaDungeon_1,
        TutorialScript_EnhanceDungeon_0,
        TutorialScript_EnhanceDungeon_1,
        TutorialScript_StartGame_3,
        TutorialScript_DefaultUpgrade_0,
        TutorialScript_DefaultUpgrade_1,
        TutorialEquipElemental2,
        TutorialEquipElemental3,
        TutorialEquipElemental4,
        TutorialEquipElemental5,
        TutorialScript_Buff_2,

        Elemental_AFC,
        Elemental_AFB,
        Elemental_AFA,
        Elemental_AFS,
        Elemental_AFSS,
        Elemental_AIC,
        Elemental_AIB,
        Elemental_AIA,
        Elemental_AIS,
        Elemental_AISS,
        Elemental_AWC,
        Elemental_AWB,
        Elemental_AWA,
        Elemental_AWS,
        Elemental_AWSS,
        Elemental_ALgC,
        Elemental_ALgB,
        Elemental_ALgA,
        Elemental_ALgS,
        Elemental_ALgSS,
        Elemental_ALC,
        Elemental_ALB,
        Elemental_ALA,
        Elemental_ALS,
        Elemental_ALSS,
        Elemental_ADC,
        Elemental_ADB,
        Elemental_ADA,
        Elemental_ADS,
        Elemental_ADSS,
        Elemental_LFC,
        Elemental_LFB,
        Elemental_LFA,
        Elemental_LFS,
        Elemental_LFSS,
        Elemental_LIC,
        Elemental_LIB,
        Elemental_LIA,
        Elemental_LIS,
        Elemental_LISS,
        Elemental_LWC,
        Elemental_LWB,
        Elemental_LWA,
        Elemental_LWS,
        Elemental_LWSS,
        Elemental_LLgC,
        Elemental_LLgB,
        Elemental_LLgA,
        Elemental_LLgS,
        Elemental_LLgSS,
        Elemental_LLC,
        Elemental_LLB,
        Elemental_LLA,
        Elemental_LLS,
        Elemental_LLSS,
        Elemental_LDC,
        Elemental_LDB,
        Elemental_LDA,
        Elemental_LDS,
        Elemental_LDSS,
        Elemental_PFC,
        Elemental_PFB,
        Elemental_PFA,
        Elemental_PFS,
        Elemental_PFSS,
        Elemental_PIC,
        Elemental_PIB,
        Elemental_PIA,
        Elemental_PIS,
        Elemental_PISS,
        Elemental_PWC,
        Elemental_PWB,
        Elemental_PWA,
        Elemental_PWS,
        Elemental_PWSS,
        Elemental_PLgC,
        Elemental_PLgB,
        Elemental_PLgA,
        Elemental_PLgS,
        Elemental_PLgSS,
        Elemental_PLC,
        Elemental_PLB,
        Elemental_PLA,
        Elemental_PLS,
        Elemental_PLSS,
        Elemental_PDC,
        Elemental_PDB,
        Elemental_PDA,
        Elemental_PDS,
        Elemental_PDSS,
        ShowInfo,
        AllLevelUp,
        PresetIsEmptyDesc,
        PresetSaveTitle,

        net_themessge_etd_firesspackage0,
        net_themessge_etd_firesspackage1,
        net_themessge_etd_firesspackage2,
        net_themessge_etd_watersspackage0,
        net_themessge_etd_watersspackage1,
        net_themessge_etd_watersspackage2,
        net_themessge_etd_windsspackage0,
        net_themessge_etd_windsspackage1,
        net_themessge_etd_windsspackage2,
        net_themessge_etd_lightingsspackage0,
        net_themessge_etd_lightingsspackage1,
        net_themessge_etd_lightingsspackage2,
        net_themessge_etd_lightsspackage0,
        net_themessge_etd_lightsspackage1,
        net_themessge_etd_lightsspackage2,
        net_themessge_etd_darknesssspackage0,
        net_themessge_etd_darknesssspackage1,
        net_themessge_etd_darknesssspackage2,
        net_themessage_etd_golddungeonpackage0,
        net_themessage_etd_golddungeonpackage1,
        net_themessage_etd_golddungeonpackage2,
        net_themessage_etd_golddungeonpackage3,
        net_themessage_etd_golddungeonpackage4,
        net_themessage_etd_golddungeonpackage5,
        net_themessage_etd_golddungeonpackage6,
        net_themessage_etd_golddungeonpackage7,
        net_themessage_etd_golddungeonpackage8,
        net_themessage_etd_golddungeonpackage9,
        net_themessage_etd_diadungeonpackage0,
        net_themessage_etd_diadungeonpackage1,
        net_themessage_etd_diadungeonpackage2,
        net_themessage_etd_diadungeonpackage3,
        net_themessage_etd_diadungeonpackage4,
        net_themessage_etd_diadungeonpackage5,
        net_themessage_etd_diadungeonpackage6,
        net_themessage_etd_diadungeonpackage7,
        net_themessage_etd_diadungeonpackage8,
        net_themessage_etd_diadungeonpackage9,
        net_themessage_etd_enhancedungeonpackage0,
        net_themessage_etd_enhancedungeonpackage1,
        net_themessage_etd_enhancedungeonpackage2,
        net_themessage_etd_enhancedungeonpackage3,
        net_themessage_etd_enhancedungeonpackage4,
        net_themessage_etd_enhancedungeonpackage5,
        net_themessage_etd_enhancedungeonpackage6,
        net_themessage_etd_enhancedungeonpackage7,
        net_themessage_etd_enhancedungeonpackage8,
        net_themessage_etd_enhancedungeonpackage9,
        net_themessage_etd_weeklydungeonpackage0,
        net_themessage_etd_weeklysummonpackage0,
        net_themessage_etd_weeklydungeonpackageForDia,
        net_themessage_etd_weeklysummonpackageForDia,

        Purchaseable,
        WeeklyPackage,

        Research_IncreaseBaseAtkPower,
        Research_IncreaseCriticalRate,
        Research_IncreaseCriticalPower,
        Research_IncreaseTotalAtkRate,
        Research_IncreaseAttackSpeed,
        Research_IncreaseMaxHp,
        Research_IncreaseHealAmountPerSecond,
        Research_IncreaseDefenceRate,
        Research_DecreaseEnhancementCost,
        Research_IncreaseEnhancementProbability,
        Research_IncreaseResearchSpeed,
        Research_DecreaseResearchCost,
        Research_IncreaseLabSlot,
        Research_IncreaseGameSpeed,
        Research_IncreaseOfflineReward,
        Research_IncreaseNormalStageReward,
        Research_IncreaseDungeonReward,
        Research_ContainerTitle0,
        Research_ContainerTitle1,
        Research_ContainerTitle2,
        Research_ContainerTitle3,
        Research_ContainerTitle4,
        Research_ContainerTitle5,

        Research_Title,

        Research_IncreaseBaseAtkPower_Desc,
        Research_IncreaseCriticalRate_Desc,
        Research_IncreaseCriticalPower_Desc,
        Research_IncreaseTotalAtkRate_Desc,
        Research_IncreaseAttackSpeed_Desc,
        Research_IncreaseMaxHp_Desc,
        Research_IncreaseHealAmountPerSecond_Desc,
        Research_IncreaseDefenceRate_Desc,
        Research_DecreaseEnhancementCost_Desc,
        Research_IncreaseEnhancementProbability_Desc,
        Research_IncreaseResearchSpeed_Desc,
        Research_DecreaseResearchCost_Desc,
        Research_IncreaseLabSlot_Desc,
        Research_IncreaseGameSpeed_Desc,
        Research_IncreaseOfflineReward_Desc,
        Research_IncreaseNormalStageReward_Desc,
        Research_IncreaseDungeonReward_Desc,
        Research_NotEnoughLabSlot,
        Research_Cancel,

        CompleteImmediately,
        Research_Start,
        ReleaseSlot,
        Research_Complete,
        Research_Cancel_Desc,
        Research_ImmediatelyCompleteCheck,

        Research_Researching,
        NoMoreResearch,
        Research_IncreaseDarkDiaPerSec,
        Research_IncreaseCreateStorage,
        Research_IncreaseSaveStorage,
        Research_IncreaseDarkDiaPerSec_Desc,
        Research_IncreaseCreateStorage_Desc,
        Research_IncreaseSaveStorage_Desc,
        Save,
        Research_ContainerTitle6,
        Research_ContainerGroupTitle0,
        Research_ContainerGroupTitle1,
        Research_ContainerGroupTitle2,
        Laboratory,
        Refinery,
        CreateDarkDiaPerSec,
        NotYet,
        SpecialLab_Desc,
        SpecialLab_Title,

        Dungeon_DarkDiaDungeon,
        Dungeon_DarkDiaDungeonDescription,
        Dungeon_DarkDiaDungeonGoal,

        FailsTitle,
        TryAgain,
        MyCount,
        GoalCount,

        AnotherUserTaking,
        PlunderBattle,
        Settlement,
        LostReward,
        EarnReward,
        Settle,
        Empty,
        Raiding,
        Stop,
        Raided,
        Plunder,
        Raid,
        AttackerDesc,
        Duration,
        Earnable,
        Plunderable,
        Protect,
        Stair,
        Zone,
        MyState,
        PlunderBattleDesc,
        StorageDesc,
        NewContents,
        TutorialScript_Research_0,
        TutorialScript_Research_1,
        TutorialScript_Research_2,
        TutorialScript_Research_3,
        TutorialScript_Research_4,
        Quest_AnyResearchCompleate,
        TutorialScript_Raid_0,
        TutorialScript_Raid_1,
        TutorialScript_Raid_2,
        TutorialScript_Raid_3,

        RaidGuideDesc,
        Dungeon_Toast_ExitDescriptionInDarkDia,
        AlreadyRaid,
        Protection,
        IsProtectedDesc,
        ProtectionDesc,
        MoveCurrStage,
        Good_VIP,
        Good_IncreaseStageReward,
        Good_IncreaseGameSpeed,
        Good_IncreaseDungeonReward,
        Good_IncreaseLabSpeed,
        Purchase,

        VIPBenefit,
        VIPRewardBox,
        VIPPreviewBenefit,
        NoBenefit,
        VIPTitle,
        VIPGetReward,
        Daily,
        GrowPassTitle,
        StagePass_Tab,
        ElementalPass_Tab,
        RunePass_Tab,
        StagePassTitle,
        ElementalPassTitle,
        RunePassTitle,
        GrowPass_CurrStage,
        GrowPass_CurrElementalSummon,
        GrowPass_CurrRuneSummon,
        GrowPass_NReward,
        GrowPass_PReward,
        StagePassDesc,
        ElementalPassDesc,
        RunePassDesc,
        AccountPurchase,
        GrowPass_GoalStage,
        GrowPass_GoalElementalSummon,
        GrowPass_GoalRuneSummon,

        GrowPass_StageLastRewardDesc,
        GrowPass_ElementalSummonLastRewardDesc,
        GrowPass_RuneSummonLastRewardDesc,

        Rating_Title,
        Rating_Desc,
        ItsOk,
        Sure,
        SelectElemental,

        Guild_Title,
        Guild_Name,
        Guild_NameDesc,
        Guild_Info,
        Guild_InfoDesc,
        Correction,
        AutoJoin,
        ApproveJoin,
        NeededStage,
        Guild_Creation,
        Guild_Recommend,
        Guild_GuildCreation,
        Guild_GuildMark,
        Guild_Background,
        Guild_MainSymbol,
        Guild_SubSymbol,
        Guild_NameError0,
        Guild_NameError1,
        Guild_Join,
        Guild_ApplyJoin,
        Guild_JoinType,
        Guild_Master,
        Guild_GiftBox_Normal0,
        Guild_GiftBox_Normal1,
        Guild_GiftBox_Normal2,
        Guild_GiftBox_Rare0,
        Guild_GiftBox_Rare1,
        Guild_GiftBox_Rare2,
        Guild_GiftBox_Unique0,
        Guild_GiftBox_Unique1,
        Guild_GiftBox_Unique2,
        Guild_GiftBox_Epic0,
        Guild_GiftBox_Epic1,
        Guild_GiftBox_Epic2,
        Guild_GiftBox_Legendary0,
        Guild_GiftBox_Legendary1,
        Guild_GiftBox_Legendary2,
        Guild_Donation,
        Guild_BoxKey,
        Guild_GiftBox,
        Guild_InfoMenu,
        Guild_MemberMenu,
        Guild_DungeonMenu,
        Guild_ShopMenu,
        Guild_NotAbailableSettlement,
        Guild_WithdrawSuccessMessage,
        Guild_WithdrawErrorMessage,
        Guild_WithdrawWarringMessage,
        Guild_Contribution,
        Guild_LastLogin,
        Guild_Manage,
        Guild_Withdrawal,
        Guild_RaidTitle,
        Guild_RaidBox,
        Guild_ExpelDesc,
        Guild_ExpelSuccess,
        Dungeon_GuildRaidDungeon,
        Dungeon_GuildRaidDungeonDescription,
        Dungeon_GuildRaidDungeonGoal,
        Guild_NormalRaidBox,
        Guild_RareRaidBox,
        Guild_UniqueRaidBox,
        Guild_GetRaidBoxes,
        Guild_NoRaidBox,
        Guild_RaidLog,
        Weekly_Purchase,
        Daily_Purchase,
        None_Purchase,
        Guild_ApproveErrorMessage0,
        Guild_ApproveErrorMessage1,
        Guild_ApplyApplicant,
        Guild_RejectApplicant,
        Guild_RaidDesc,
        Guild_RaidBoxDesc,
        Guild_RankingTitle,
        Guild_ApplicantList,
        Guild_EmptySlot,
        Guild_JoinErrorMessage,
        Guild_PreApplyMessage,
        Guild_JoinSuccess,
        Guild_ApplySuccess,
        Guild_StageLevelInsufficient,
        Online,
        MinutesAgo,
        HoursAgo,
        DaysAgo,
        Guild_GiftBoxDesc,
        Guild_MasterNominate,
        Guild_MasterNominateDesc,
        Guild_MasterNominateSuccess,
        Guild_Approved,
        Guild_Reject,

        StepupTitle,
        net_themessage_etd_elementalstepup,
        net_themessage_etd_runestepup,
        Free,
        Shop_Package,
        Shop_DailyWeekly,
        Shop_Default,
        Easy,
        Normal,
        Hard,
        VeryHard,
        RomanNumerals1,
        RomanNumerals2,
        RomanNumerals3,
        RomanNumerals4,
        StageTitle0,
        StageTitle1,
        StageTitle2,
        StageTitle3,
        StageTitle4,
        StageTitle5,
        StageTitle6,
        StageTitle7,
        StageTitle8,
        StageTitle9,
        AutoCloseFewSeconds,
        Claimed,
        NextChallenge,
        FailChallengeDescription,
        Summon,
        GoldUpgrade,
        ResearchEnhancement,

        GoodType_Dia_Title,
        GoodType_Gold_Title,
        GoodType_ElementalEnhancementStone_Title,
        GoodType_RuneEnhancementStone_Title,
        GoodType_ShowAds_Title,
        GoodType_SummonElemental_Title,
        GoodType_SummonRune_Title,
        GoodType_SummonElementalTicket_Title,
        GoodType_SummonRuneTicket_Title,
        GoodType_RemoveAds_Title,
        GoodType_GoldDungeonTicket_Title,
        GoodType_GemDungeonTicket_Title,
        GoodType_EnhanceDungeonTicket_Title,
        GoodType_DungeonTickets_Title,
        GoodType_DarkDia_Title,
        GoodType_SpecialLab_Title,
        GoodType_RaidTicket_Title,
        GoodType_Protection_Title,
        GoodType_VIP_Title,
        GoodType_IncreaseStageReward_Title,
        GoodType_IncreaseGameSpeed_Title,
        GoodType_IncreaseDungeonReward_Title,
        GoodType_IncreaseLabSpeed_Title,
        GoodType_SummonElementalS_Title,
        GoodType_SummonElementalSS_Title,
        GoodType_SummonRuneS_Title,
        GoodType_SummonRuneSS_Title,
        GoodType_GuildExp_Title,
        GoodType_GuildGiftBoxPoint_Title,
        GoodType_GuildGiftBoxExp_Title,
        GoodType_GuildRaidTicket_Title,
        GoodType_GuildToken_Title,
        GoodType_Dia_Desc,
        GoodType_Gold_Desc,
        GoodType_ElementalEnhancementStone_Desc,
        GoodType_RuneEnhancementStone_Desc,
        GoodType_ShowAds_Desc,
        GoodType_SummonElemental_Desc,
        GoodType_SummonRune_Desc,
        GoodType_SummonElementalTicket_Desc,
        GoodType_SummonRuneTicket_Desc,
        GoodType_RemoveAds_Desc,
        GoodType_GoldDungeonTicket_Desc,
        GoodType_GemDungeonTicket_Desc,
        GoodType_EnhanceDungeonTicket_Desc,
        GoodType_DungeonTickets_Desc,
        GoodType_DarkDia_Desc,
        GoodType_SpecialLab_Desc,
        GoodType_RaidTicket_Desc,
        GoodType_Protection_Desc,
        GoodType_VIP_Desc,
        GoodType_IncreaseStageReward_Desc,
        GoodType_IncreaseGameSpeed_Desc,
        GoodType_IncreaseDungeonReward_Desc,
        GoodType_IncreaseLabSpeed_Desc,
        GoodType_SummonElementalS_Desc,
        GoodType_SummonElementalSS_Desc,
        GoodType_SummonRuneS_Desc,
        GoodType_SummonRuneSS_Desc,
        GoodType_GuildExp_Desc,
        GoodType_GuildGiftBoxPoint_Desc,
        GoodType_GuildGiftBoxExp_Desc,
        GoodType_GuildRaidTicket_Desc,
        GoodType_GuildToken_Desc,
        Source,
        Usage,
        Source_NormalStage,
        Source_GoldDungeon,
        Source_DiaDungeon,
        Source_EnhanceDungeon,
        Source_OfflineReward,
        Source_FreeGift,
        Source_Shop,
        Source_BattlePass,
        Source_GrowPass,
        Source_GuildShop,
        Source_VIPReward,
        Source_Raid,
        Source_Research,
        Source_PerHour,
        Source_GuildDonation,
        Source_GuildGiftBox,
        Source_GuildRaidBox,
        Usage_GoldUpgrade,
        Usage_DiaUpgrade,
        Usage_SummonElemental,
        Usage_SummonRune,
        Usage_Protection,
        Usage_EnhanceElemental,
        Usage_EnhanceRune,
        Usage_Shop,
        Usage_Immediately,
        Usage_Dungeon,
        Usage_Research,
        Usage_Raid,
        Usage_GuildGiftBox,
        Usage_GuildRaid,
        Usage_GuildShop,
    }

    public enum ObjectPoolType
    {
        Bullet,
        Particle,
        Enemy
    }

    public enum ParticleType
    {
        ParticleF,
        ParticleI,
        ParticleL,
        ParticleLg,
        ParticleEnemyAttack,
        ParticleLgBig,
    }

    public enum EnhancementType
    {
        Elemental,
        Rune
    }

    public enum TimeResetType
    {
        None,
        Daily,
        Weekly,
        Monthly,
        Repeat
    }

    public enum MissionType
    {
        None,
        DailyLogin,
        KillEnemy,
        ClearGoldDungeon,
        ClearDiaDungeon,
        ClearEnhanceDungeon,       
        ClearNormalStage,
        ClearAnyDungeon,
        
        SummonElemental,
        SummonRune,
        Enhance,
        Upgrade,
        
        DailyMission0,
        DailyMission1,
        DailyMission2,
        WeeklyMission0,
        WeeklyMission1,
        WeeklyMission2,
    }

    public enum ProductType
    {
        SummonElementalForAds,
        SummonElementalForDia,
        SummonElementalForDias,

        SummonRuneForAds,
        SummonRuneForDia,
        SummonRuneForDias,
        
        net_themessage_etc_dia0,
        net_themessage_etc_dia1,
        net_themessage_etc_dia2,
        net_themessage_etc_dia3,
        net_themessage_etc_dia4,
        net_themessage_etc_dia5,
        net_themessage_etc_newbiepackage,
        net_themessage_etc_removeadspackage,
        net_themessage_etd_removeadspackage,
        net_themessage_etc_summonticketpackage0,
        
        net_themessage_etd_stagepackage0,
        net_themessage_etd_stagepackage1,
        net_themessage_etd_stagepackage2,
        net_themessage_etd_stagepackage3,
        net_themessage_etd_stagepackage4,
        net_themessage_etd_stagepackage5,
        net_themessage_etd_stagepackage6,
        net_themessage_etd_stagepackage7,
        net_themessage_etd_stagepackage8,
        net_themessage_etd_stagepackage9,
        
        FirstPurchaseReward,
        
        net_themessage_etc_premiumpass,
        net_themessage_etc_masterpass,
        
        GoldDungeonTicketForDia,
        EnhanceDungeonTicketForDia,
        
        net_themessge_etd_firesspackage0,
        net_themessge_etd_firesspackage1,
        net_themessge_etd_firesspackage2,
        net_themessge_etd_watersspackage0,
        net_themessge_etd_watersspackage1,
        net_themessge_etd_watersspackage2,
        net_themessge_etd_windsspackage0,
        net_themessge_etd_windsspackage1,
        net_themessge_etd_windsspackage2,
        net_themessge_etd_lightingsspackage0,
        net_themessge_etd_lightingsspackage1,
        net_themessge_etd_lightingsspackage2,
        net_themessge_etd_lightsspackage0,
        net_themessge_etd_lightsspackage1,
        net_themessge_etd_lightsspackage2,
        net_themessge_etd_darknesssspackage0,
        net_themessge_etd_darknesssspackage1,
        net_themessge_etd_darknesssspackage2,
        net_themessage_etd_golddungeonpackage0,
        net_themessage_etd_golddungeonpackage1,
        net_themessage_etd_golddungeonpackage2,
        net_themessage_etd_golddungeonpackage3,
        net_themessage_etd_golddungeonpackage4,
        net_themessage_etd_golddungeonpackage5,
        net_themessage_etd_golddungeonpackage6,
        net_themessage_etd_golddungeonpackage7,
        net_themessage_etd_golddungeonpackage8,
        net_themessage_etd_golddungeonpackage9,
        net_themessage_etd_diadungeonpackage0,
        net_themessage_etd_diadungeonpackage1,
        net_themessage_etd_diadungeonpackage2,
        net_themessage_etd_diadungeonpackage3,
        net_themessage_etd_diadungeonpackage4,
        net_themessage_etd_diadungeonpackage5,
        net_themessage_etd_diadungeonpackage6,
        net_themessage_etd_diadungeonpackage7,
        net_themessage_etd_diadungeonpackage8,
        net_themessage_etd_diadungeonpackage9,
        net_themessage_etd_enhancedungeonpackage0,
        net_themessage_etd_enhancedungeonpackage1,
        net_themessage_etd_enhancedungeonpackage2,
        net_themessage_etd_enhancedungeonpackage3,
        net_themessage_etd_enhancedungeonpackage4,
        net_themessage_etd_enhancedungeonpackage5,
        net_themessage_etd_enhancedungeonpackage6,
        net_themessage_etd_enhancedungeonpackage7,
        net_themessage_etd_enhancedungeonpackage8,
        net_themessage_etd_enhancedungeonpackage9,
        net_themessage_etd_weeklydungeonpackage0,
        net_themessage_etd_weeklysummonpackage0,
        net_themessage_etd_weeklydungeonpackageForDia,
        net_themessage_etd_weeklysummonpackageForDia,
        
        ProtectionForDia0,
        ProtectionForDia1,
        ProtectionForDia2,
        net_themessage_etd_vip0,
        net_themessage_etd_vip1,
        net_themessage_etd_vip2_renew,
        net_themessage_etd_vip3,
        
        net_themessage_etd_stagepass0,
        net_themessage_etd_stagepass1,
        net_themessage_etd_stagepass2,
        net_themessage_etd_stagepass3,
        net_themessage_etd_stagepass4,
        net_themessage_etd_elementalsummonpass0,
        net_themessage_etd_elementalsummonpass1,
        net_themessage_etd_elementalsummonpass2,
        net_themessage_etd_elementalsummonpass3,
        net_themessage_etd_elementalsummonpass4,
        net_themessage_etd_runesummonpass0,
        net_themessage_etd_runesummonpass1,
        net_themessage_etd_runesummonpass2,
        net_themessage_etd_runesummonpass3,
        net_themessage_etd_runesummonpass4,
        
        net_themessage_etd_elementalstepup0,
        net_themessage_etd_elementalstepup1,
        net_themessage_etd_elementalstepup2,
        net_themessage_etd_elementalstepup3,
        net_themessage_etd_elementalstepup4,
        net_themessage_etd_elementalstepup5,
        net_themessage_etd_elementalstepup6,
        net_themessage_etd_runestepup0,
        net_themessage_etd_runestepup1,
        net_themessage_etd_runestepup2,
        net_themessage_etd_runestepup3,
        net_themessage_etd_runestepup4,
        net_themessage_etd_runestepup5,
        net_themessage_etd_runestepup6,
        net_themessage_etd_dailydungeon0,
        net_themessage_etd_dailydungeon1,
    }

    public enum IAPType
    {
        net_themessage_etc_dia0,
        net_themessage_etc_dia1,
        net_themessage_etc_dia2,
        net_themessage_etc_dia3,
        net_themessage_etc_dia4,
        net_themessage_etc_dia5,
        net_themessage_etc_newbiepackage,
        net_themessage_etc_removeadspackage,
        net_themessage_etd_removeadspackage,
        net_themessage_etc_summonticketpackage0,
        
        net_themessage_etd_stagepackage0,
        net_themessage_etd_stagepackage1,
        net_themessage_etd_stagepackage2,
        net_themessage_etd_stagepackage3,
        net_themessage_etd_stagepackage4,
        net_themessage_etd_stagepackage5,
        net_themessage_etd_stagepackage6,
        net_themessage_etd_stagepackage7,
        net_themessage_etd_stagepackage8,
        net_themessage_etd_stagepackage9,
        
        net_themessage_etc_premiumpass,
        net_themessage_etc_masterpass,
        
        net_themessge_etd_firesspackage0,
        net_themessge_etd_firesspackage1,
        net_themessge_etd_firesspackage2,
        net_themessge_etd_watersspackage0,
        net_themessge_etd_watersspackage1,
        net_themessge_etd_watersspackage2,
        net_themessge_etd_windsspackage0,
        net_themessge_etd_windsspackage1,
        net_themessge_etd_windsspackage2,
        net_themessge_etd_lightingsspackage0,
        net_themessge_etd_lightingsspackage1,
        net_themessge_etd_lightingsspackage2,
        net_themessge_etd_lightsspackage0,
        net_themessge_etd_lightsspackage1,
        net_themessge_etd_lightsspackage2,
        net_themessge_etd_darknesssspackage0,
        net_themessge_etd_darknesssspackage1,
        net_themessge_etd_darknesssspackage2,
        net_themessage_etd_golddungeonpackage0,
        net_themessage_etd_golddungeonpackage1,
        net_themessage_etd_golddungeonpackage2,
        net_themessage_etd_golddungeonpackage3,
        net_themessage_etd_golddungeonpackage4,
        net_themessage_etd_golddungeonpackage5,
        net_themessage_etd_golddungeonpackage6,
        net_themessage_etd_golddungeonpackage7,
        net_themessage_etd_golddungeonpackage8,
        net_themessage_etd_golddungeonpackage9,
        net_themessage_etd_diadungeonpackage0,
        net_themessage_etd_diadungeonpackage1,
        net_themessage_etd_diadungeonpackage2,
        net_themessage_etd_diadungeonpackage3,
        net_themessage_etd_diadungeonpackage4,
        net_themessage_etd_diadungeonpackage5,
        net_themessage_etd_diadungeonpackage6,
        net_themessage_etd_diadungeonpackage7,
        net_themessage_etd_diadungeonpackage8,
        net_themessage_etd_diadungeonpackage9,
        net_themessage_etd_enhancedungeonpackage0,
        net_themessage_etd_enhancedungeonpackage1,
        net_themessage_etd_enhancedungeonpackage2,
        net_themessage_etd_enhancedungeonpackage3,
        net_themessage_etd_enhancedungeonpackage4,
        net_themessage_etd_enhancedungeonpackage5,
        net_themessage_etd_enhancedungeonpackage6,
        net_themessage_etd_enhancedungeonpackage7,
        net_themessage_etd_enhancedungeonpackage8,
        net_themessage_etd_enhancedungeonpackage9,
        net_themessage_etd_weeklydungeonpackage0,
        net_themessage_etd_weeklysummonpackage0,
        
        net_themessage_etd_speciallab,
        net_themessage_etd_vip0,
        net_themessage_etd_vip1,
        net_themessage_etd_vip2_renew,
        net_themessage_etd_vip3,
        
        net_themessage_etd_stagepass0,
        net_themessage_etd_stagepass1,
        net_themessage_etd_stagepass2,
        net_themessage_etd_stagepass3,
        net_themessage_etd_stagepass4,
        net_themessage_etd_elementalsummonpass0,
        net_themessage_etd_elementalsummonpass1,
        net_themessage_etd_elementalsummonpass2,
        net_themessage_etd_elementalsummonpass3,
        net_themessage_etd_elementalsummonpass4,
        net_themessage_etd_runesummonpass0,
        net_themessage_etd_runesummonpass1,
        net_themessage_etd_runesummonpass2,
        net_themessage_etd_runesummonpass3,
        net_themessage_etd_runesummonpass4,
        
        net_themessage_etd_elementalstepup0,
        net_themessage_etd_elementalstepup2,
        net_themessage_etd_elementalstepup4,
        net_themessage_etd_elementalstepup6,
        net_themessage_etd_runestepup0,
        net_themessage_etd_runestepup2,
        net_themessage_etd_runestepup4,
        net_themessage_etd_runestepup6,
        net_themessage_etd_dailydungeon0,
        net_themessage_etd_dailydungeon1,
    }

    public enum QuestType
    {
        KillEnemy,
        SummonElemental,
        SummonRune,
        
        ClearNormalStage,
        ClearGoldDungeon,
        ClearDiaDungeon,
        ClearEnhanceDungeon,
        
        UpgradeElementalSlot,
        EquipElemental,
        
        UpgradeRuneSlot,
        EquipRune,
        
        UpgradeProjector,
        EquipElementalWithProjector,
        EquipRuneWithProjector,
        
        UpgradeATK,
        UpgradeMaxHp,
        UpgradeIncreaseHealAmount,
        
        EnhanceElemental,
        EnhanceRune,
        DisassembleRune,
        
        ClickGameSpeed, 
        ClickGameSpeedBuff,
        
        AnyResearchCompleate,
    }

    // 순서 바꾸면 클리어 한 최고 레벨이 바뀜
    public enum StageType
    {
        Normal = 0,
        GoldDungeon = 1,
        DiaDungeon,
        EnhanceDungeon,
        DarkDiaDungeon,
        GuildRaidDungeon,
    }

    public enum ToastType
    {
        None,
        TransientMessage,
        BoxMessage,
        Loading,
        Reward,
        GoodInfo
    }

    public enum ReddotType
    {
        None,
        ElementalLevelUp,
        MissionDaily,
        MissionWeekly,
        MissionRepeat,
        ReceiveableMail,
        FreeGift,
        Attendance,
        FirstPurchased,
        Pass,
        Research,
        RaidSettle,
        VipReward,
        
        StagePass,
        ElementalPass,
        RunePass,
        GuildDonation,
        GuildGiftBox,
        GuildApplicant,
        GuildRaidBox
    }

    public enum SlotType
    {
        UnitSlot,
        EquipSlot
    }

    public enum UnlockType
    {
        None,
        DungeonMenu,
        GoldDungeon,
        DiaDungeon,
        EnhanceDungeon,
        ShopMenu,
        SummonElemental,
        SummonRune,
        StageLevel,
        GameSpeedPanel,
        BuffPanel,
        Attendance,
        FirstPurchase,
        Pass,
        UpgradeMenu,
        GetElemental,
        Research,
        Raid,
        GrowPass,
        Rating,
        Guild
    }

    public enum FreeGiftType
    {
        FreeCoin,
        SummonTicket,
        DungeonTicket
    }

    public enum SoundType
    {
        BGM,
        SFX
    }

    public enum AudioClipType
    {
        BGM,
        Tic,
        KillEnemy
    }

    public enum TutorialType
    {
        None = -1,
        EquipElemental,
        EquipRune,
        GameStart,
        GameSpeed,
        Buff,
        
        DescriptionActiveSlot,
        DescriptionLinkSlot,
        DescriptionPassiveSlot,
        
        SelectElementalSlot,
        EquipElementalButton,
        EquipLinkSlot,
        EquipRuneSlot,
        Tag,
        
        SummonElemental,
        UpgradeElementalSlot,
        DescriptionSlot,
        
        ClickQuestPanel,
        SummonRune,
        UpgradeRuneSlot,
        GoldDungeon,
        DiaDungeon,
        EnhanceDungeon,
        DefaultUpgrade,
        Research,
        Raid,
    }

    public enum AttendanceType
    {
        SevenDay,
    }

    public enum BattlePassType
    {
        Normal,
        Premium
    }

    public enum ResearchType
    {
        None = -1,
        IncreaseBaseAtkPower,
        IncreaseCriticalRate,
        IncreaseCriticalPower,
        IncreaseTotalAtkRate,
        IncreaseAttackSpeed,
        
        IncreaseMaxHp,
        IncreaseHealAmountPerSecond,
        IncreaseDefenceRate,
        
        DecreaseEnhancementCost,
        IncreaseEnhancementProbability,
        
        IncreaseResearchSpeed,
        DecreaseResearchCost,
        IncreaseLabSlot,
        
        IncreaseGameSpeed,
        
        IncreaseOfflineReward,
        IncreaseNormalStageReward,
        IncreaseDungeonReward,
        IncreaseDarkDiaPerSec,
        IncreaseCreateStorage,
        IncreaseSaveStorage,
    }

    public enum PassType
    {
        StagePass,
        ElementalPass,
        RunePass
    }

    public enum GuildRewardType
    {
        Donation,
        GiftBox,
        Shop,
        RaidBox,
    }

    public enum ViewAnimationType
    {
        None,
        Popup,
        SlideUp,
    }
    
    public enum ReduceType
    {
        Vip,
        Research,
    }
}